### ISSUE TITLE
python errors on kci_build make_kselftest

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1323]
During staging logs investigation i noticed error generated by one of kernelci commands:
https://bot.staging.kernelci.org/job/kernel-build/74684/console
```
./kci_build make_kselftest
Traceback (most recent call last):
  File "/scratch/kernelci-core/./kci_build", line 427, in <module>
    status = opts.command(configs, opts)
  File "/scratch/kernelci-core/./kci_build", line 338, in __call__
    if not step.is_enabled():
  File "/scratch/kernelci-core/kernelci/build.py", line 1477, in is_enabled
    return self._check_min_kver(5, 10)
  File "/scratch/kernelci-core/kernelci/build.py", line 755, in _check_min_kver
    m = self._kver_re.match(kver)
AttributeError: 'MakeSelftests' object has no attribute '_kver_re'
Build result: 1

bmeta.json
```
Build configuration was:
```
{
    "build": {
        "duration": 481.46804451942444,
        "status": "PASS"
    },
    "environment": {
        "arch": "x86_64",
        "compiler": "gcc",
        "compiler_version": "10",
        "compiler_version_full": "gcc (Debian 10.2.1-6) 10.2.1 20210110",
        "cross_compile": "",
        "cross_compile_compat": "",
        "make_opts": {
            "KBUILD_BUILD_USER": "KernelCI"
        },
        "name": "gcc-10",
        "platform": {
            "uname": [
                "Linux",
                "build-j74684-x86-64-gcc-10-x86-64-defconfig-preempt-rt-hh89s",
                "5.10.90+",
                "#1 SMP Sat Mar 5 10:09:49 UTC 2022",
                "x86_64",
                ""
            ]
        },
        "use_ccache": true
    },
    "kernel": {
        "defconfig": "x86_64_defconfig",
        "defconfig_expanded": "x86_64_defconfig+kernel/configs/preempt_rt.config",
        "defconfig_extras": [
            "preempt_rt"
        ],
        "defconfig_full": "x86_64_defconfig+preempt_rt",
        "endianness": "little",
        "fragments": [
            "kernelci.config"
        ],
        "image": "bzImage",
        "publish_path": "kernelci/staging-next/staging-next-20220726.0/x86_64/x86_64_defconfig+preempt_rt/gcc-10",
        "text_offset": "0x01000000",
        "vmlinux_bss_size": 925696,
        "vmlinux_data_size": 2729344,
        "vmlinux_file_size": 74069624,
        "vmlinux_text_size": 16790216
    },
    "revision": {
        "branch": "staging-next",
        "commit": "edc50366064e833c5af81098f099360deda10682",
        "describe": "staging-next-20220726.0",
        "describe_verbose": "v5.19-rc8-13106-gedc50366064e",
        "tree": "kernelci",
        "url": "https://github.com/kernelci/linux.git"
    }
}
```

**Comment by gctucker** [comment]
Fixed as part of the #1300 review.
