### ISSUE TITLE
kci_test: 'cros_flash_kernel' undefined error

### ISSUE THREAD

**Issue by JenySadadia** [kernelci/kernelci-core#1326]
While getting familiar with chromeos, I tried to generate and submit a few jobs.

kernelci-core git branch: `chromeos`
Command: 
```
./kci_test generate --install-path=linux/build/_install_ --plan=cros-tast --target=hp-x360-12b-ca0500na-n4000-octopus --storage=https://chromeos.kernelci.org

Traceback (most recent call last):
  File "./kci_test", line 317, in <module>
    status = opts.command(configs, opts)
  File "./kci_test", line 260, in __call__
    job = lab_api.generate(params, device_config, plan_config,
  File "/home/jeny/kernelCI/kernelci-core-env/src/kernelci-core/kernelci/lab/lava/__init__.py", line 88, in generate
    data = template.render(params)
  File "/home/jeny/kernelCI/kernelci-core-env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jeny/kernelCI/kernelci-core-env/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "config/lava/chromeos/cros-tast.jinja2", line 1, in top-level template code
    {% extends base_template|default('chromeos/cros-boot.jinja2') %}
  File "config/lava/chromeos/cros-boot.jinja2", line 1, in top-level template code
    {% extends 'base/kernel-ci-base.jinja2' %}
  File "config/lava/base/kernel-ci-base.jinja2", line 83, in top-level template code
    {% block actions %}{% endblock %}
  File "config/lava/chromeos/cros-tast.jinja2", line 3, in block 'actions'
    {{ super() }}
  File "config/lava/chromeos/cros-boot.jinja2", line 24, in block 'actions'
    url: {{ cros_flash_kernel.base_url }}{{ cros_flash_kernel.image }}
  File "/home/jeny/kernelCI/kernelci-core-env/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'cros_flash_kernel' is undefined
```

**Comment by JenySadadia** [comment]
As a workaround, I added a few params to `cros-tast` test plan in `test-configs-chromeos.yaml` file.
That fixed the issue.

```
cros-tast: &cros-tast
    pattern: 'chromeos/cros-tast.jinja2'
    filters: *cros-filters
    params: &cros-tast-params
      job_timeout: '60'
      docker_image: 'kernelci/cros-tast'
      cros_flash_nfs:
        base_url: 'https://storage.kernelci.org/images/rootfs/debian/bullseye-cros-flash/20220718.0/amd64/'
        initrd: 'initrd.cpio.gz'
        initrd_compression: 'gz'
        rootfs: 'full.rootfs.tar.xz'
        rootfs_compression: 'xz'
      cros_flash_kernel:
        base_url: 'http://storage.chromeos.kernelci.org/images/kernel/v5.10.112-x86-chromebook/'
        image: 'kernel/bzImage'
        modules: 'modules.tar.xz'
        modules_compression: 'xz'
      cros_image:
        base_url: 'https://storage.chromeos.kernelci.org/images/rootfs/chromeos/chromiumos-octopus/20220520.0/amd64/'
        flash_tarball: 'cros-flash.tar.gz'
        flash_tarball_compression: 'gz'
        tast_tarball: 'tast.tgz'
      reference_kernel:
        image: 'https://storage.chromeos.kernelci.org/images/kernel/chromeos-octopus-4.14.243/vmlinuz-4.14.243'
        modules: 'https://storage.chromeos.kernelci.org/images/kernel/chromeos-octopus-4.14.243/modules-4.14.243.tar.gz'
      block_device: mmcblk0
```

I am not sure if this is the proper way to fix this.

**Comment by gctucker** [comment]
The kernel should be specific to the device, not the test plan.  Which revision of kernelci-core were you using when you saw this problem?

**Comment by JenySadadia** [comment]
This is the build meta-data I used: https://storage.chromeos.kernelci.org/kernelci/chromeos-stable/chromeos-stable-20220726.0/x86_64/cros---chromeos-5.10-x86_64-chromeos-intel-pineview.flavour.config+x86-chromebook+CONFIG_MODULE_COMPRESS=n/clang-14/

kernelci-core revision:
branch: chromeos
commit: 5d982167ebaa9e897438da9f2757fd0d8da16080

**Comment by nuclearcat** [comment]
Hi! Is issue solved?

**Comment by JenySadadia** [comment]
> Hi! Is issue solved?

Not yet. I observed it when I was testing for coral last week.

**Comment by nuclearcat** [comment]
Can you please try to specify target as "hp-x360-12b-ca0010nr-n4020-octopus_chromeos" or similar? (suffix _chromeos), as in test-configs-chromeos.yaml we have different device definition names for devices that are supposed to be tested with ChromeOS userspace.

**Comment by nuclearcat** [comment]
Fixed by relevant commit
