### ISSUE TITLE
gcc-10_arc builds are failing due broken kernelci/staging-gcc-10_arc

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1332]
As i noticed for several days ARC builds are failing, due missing arc gcc in staging docker image kernelci/staging-gcc-10_arc
Here is relevant snippet from log:
```
+ ./kci_build init_bmeta --build-config=kernelci_staging-mainline --commit=54e1556805a19147c7cbdb511a1ee7e07645866e --describe=staging-mainline-20220801.0 --describe-verbose=v5.19-1-g54e1556805a1
Traceback (most recent call last):
  File "/scratch/kernelci-core/./kci_build", line 427, in <module>
Initialising build meta-data in /tmp/kci/linux/build
Install directory: /tmp/kci/linux/build/_install_
    status = opts.command(configs, opts)
  File "/scratch/kernelci-core/./kci_build", line 324, in __call__
    res = step.run(opts={'build_env': build_env, 'arch': args.arch})
  File "/scratch/kernelci-core/kernelci/build.py", line 1002, in run
    cc_version_full = shell_cmd(cc_version_cmd).splitlines()[0]
  File "/scratch/kernelci-core/kernelci/__init__.py", line 29, in shell_cmd
    return subprocess.check_output(cmd, shell=True).decode()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'arc-elf32-gcc --version 2>&1' returned non-zero exit status 127.
+ ./kci_build make_config --defconfig=haps_hs_smp_defconfig+kselftest
Traceback (most recent call last):
  File "/scratch/kernelci-core/./kci_build", line 427, in <module>
    status = opts.command(configs, opts)
  File "/scratch/kernelci-core/./kci_build", line 342, in __call__
    res = step.run(args.j, args.verbose, opts)
  File "/scratch/kernelci-core/kernelci/build.py", line 1156, in run
    rev, env = (bmeta[cat] for cat in ('revision', 'environment'))
  File "/scratch/kernelci-core/kernelci/build.py", line 1156, in <genexpr>
    rev, env = (bmeta[cat] for cat in ('revision', 'environment'))
KeyError: 'environment'
Build result: 1
```
Running manually docker image confirms:
```
arc-elf32-gcc --version
bash: arc-elf32-gcc: command not found
```

**Comment by gctucker** [comment]
Could you please try again manually with the new image `kernelci/staging-gcc-10:arc-kernelci`?

**Comment by gctucker** [comment]
```
$ docker run -it kernelci/staging-gcc-10:arc-kernelci arc-elf32-gcc --version
arc-elf32-gcc (ARCompact/ARCv2 ISA elf32 toolchain - build 581) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by nuclearcat** [comment]
Works fine for me now

**Comment by gctucker** [comment]
Do you mean with the new image or the regular one used in production?

**Comment by nuclearcat** [comment]
Works with new image kernelci/staging-gcc-10:arc-kernelci
Jenkins on staging still failing with same error as it uses old image.

**Comment by gctucker** [comment]
OK I see, thanks. I'm now about to update the Jenkins / k8s kernel build jobs to use the new image names, so this issue should then go away.

**Comment by nuclearcat** [comment]
We got successfull ARC build, so i guess issue can be closed: https://storage.staging.kernelci.org/kernelci/staging-mainline/staging-mainline-20220818.0/arc/haps_hs_smp_defconfig/gcc-10/logs/

**Comment by gctucker** [comment]
Yes that's fixed with the new Docker images.
