### ISSUE TITLE
Upload retry mechanism

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1333]
As i noticed by viewing jenkins logs for several days, often kernel build get completed but fails to upload due intermittent failures, sometimes DNS resolution, sometimes some http error, sometimes timeout. For example:
```
Upload path: kernelci/chromeos-stable/chromeos-stable-20220731.0/arm64/cros---chromeos-5.10-arm64-chromiumos-arm64.flavour.config/clang-14
Traceback (most recent call last):
  File "/scratch/kernelci-core/./kci_build", line 427, in <module>
    status = opts.command(configs, opts)
  File "/scratch/kernelci-core/./kci_build", line 406, in __call__
    kernelci.storage.upload_files(
  File "/scratch/kernelci-core/kernelci/storage.py", line 62, in upload_files
    resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://api.chromeos.kernelci.org/upload
```

As we know network might be unstable, i propose i can implement upload retry mechanism, that on error will try to repeat upload process several times, to avoid losing test results.

**Comment by broonie** [comment]
What I've got for my personal builders which I wanted to implement for KernelCI k8s stuff is a system where the builds drop the output into cluster local storage and then a separate task (either from cronjob or kicked by the builder) does the actual upload. This is also useful because it means that if you've got a large build job with many CPUs and slow uploads you can move the slow uploads into a smaller pod with fewer resources allocated to it.
