### ISSUE TITLE
wait.py stability issues

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1470]
As part of improving stability of kernelci jobs i will document here errors that are causing early job interruptions and if it is likely they can be handled better, to not cancel the job

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa8eb340e20>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/etc/kernelci/k8s/wait.py", line 198, in <module>
    main(args)
  File "/etc/kernelci/k8s/wait.py", line 135, in main
    pod = find_pod(core, args)
  File "/etc/kernelci/k8s/wait.py", line 39, in find_pod
    pod = core.list_namespaced_pod(namespace=args.namespace,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api/core_v1_api.py", line 15697, in list_namespaced_pod
    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api/core_v1_api.py", line 15812, in list_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py", line 240, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/dist-packages/kubernetes/client/rest.py", line 213, in request
    r = self.pool_manager.request(method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aks-kci-us-east2-dns-143f6a24.hcp.eastus2.azmk8s.io', port=443): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=job-name%3Dbuild-j307368-arm-gcc-10-u8500-defconfig&watch=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa8eb340e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by nuclearcat** [comment]
```
Upload path: kernelci/chromeos-stable/chromeos-stable-20221014.1/x86_64/cros---chromeos-5.15-x86_64-chromiumos-x86_64.flavour.config+x86-chromebook/clang-14
Traceback (most recent call last):
  File "/usr/local/bin/kci_build", line 4, in <module>
    __import__('pkg_resources').run_script('kernelci==1.1', 'kci_build')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 451, in <module>
    status = opts.command(configs, opts)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 430, in __call__
    kernelci.storage.upload_files(
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/kernelci/storage.py", line 62, in upload_files
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://api.chromeos.kernelci.org/upload
504 Server Error: Gateway Time-out for url: https://api.chromeos.kernelci.org/build
```

**Comment by nuclearcat** [comment]
```
PASS
WARNING: >1 pod found with job name build-j87342-arm-gcc-10-sama5-defconfig
[Pipeline] sh
+ grep ^Upload path: build-j87342-arm-gcc-10-sama5-defconfig.log
```
I think in this case it is at least useful to log each pod information/details.

**Comment by nuclearcat** [comment]
```
PASS
Found job on pod build-j87759-x86-64-clang-16-x86-64-defconfig-ima-gj9qq
Exception: Unable to get pod log (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'a1a3bb18-8d39-4b8d-a7a2-c579c8ee97e0', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Wed, 19 Oct 2022 08:40:02 GMT', 'Content-Length': '242'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"gke-kci-eu-west1-pool-1-4f4908d4-8xz2\" not found","reason":"NotFound","details":{"name":"gke-kci-eu-west1-pool-1-4f4908d4-8xz2","kind":"pods"},"code":404}
```

**Comment by nuclearcat** [comment]
```
total 20
-rw-r--r-- 1 root root  393 Oct 19 08:39 artifacts.json
-rw-r--r-- 1 root root 1401 Oct 19 08:39 bmeta.json
drwxr-xr-x 2 root root 4096 Oct 19 08:32 config
drwxr-xr-x 2 root root 4096 Oct 19 08:39 logs
-rw-r--r-- 1 root root 2597 Oct 19 08:39 steps.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f917ad07f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
Upload path: kernelci/staging-next/staging-next-20221019.0/riscv/defconfig/gcc-10
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.staging.kernelci.org', port=443): Max retries exceeded with url: /upload (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f917ad07f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kci_build", line 4, in <module>
    __import__('pkg_resources').run_script('kernelci==1.1', 'kci_build')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 451, in <module>
    status = opts.command(configs, opts)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 430, in __call__
    kernelci.storage.upload_files(
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/kernelci/storage.py", line 61, in upload_files
    resp = requests.post(url, headers=headers, data=data, files=files)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.staging.kernelci.org', port=443): Max retries exceeded with url: /upload (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f917ad07f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
{"reason":"Request accepted and being imported","code":202}

job build-j87774-riscv-gcc-10-defconfig deleted.  job.status:
("{'conditions': [{'type': 'Complete', 'status': 'True', 'lastProbeTime': "
 "'2022-10-19T08:39:54Z', 'lastTransitionTime': '2022-10-19T08:39:54Z'}], "
 "'startTime': '2022-10-19T08:31:17Z', 'completionTime': "
 "'2022-10-19T08:39:54Z', 'succeeded': 1}")
```
Another upload_files failure. If previous one related to possible backend malfunction, this one looks like intermittent DNS failure and it definitely require retry.

**Comment by nuclearcat** [comment]
```
PASS
Found job on pod build-j446048-arm-clang-14-assabet-defconfig-4jn7d
Exception: Unable to get pod log (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Audit-Id': '3aef8f1a-a30b-496b-a485-3e5e1b41b85c', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Thu, 03 Nov 2022 10:37:39 GMT', 'Content-Length': '213'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Get \"[https://10.240.0.6:10250/containerLogs/default/build-j446048-arm-clang-14-assabet-defconfig-4jn7d/kci-build\](https://10.240.0.6:10250/containerLogs/default/build-j446048-arm-clang-14-assabet-defconfig-4jn7d/kci-build/)": EOF","code":500}
```

**Comment by nuclearcat** [comment]
Most issues fixed by relevant patches, last one: https://github.com/kernelci/kernelci-core/pull/1479
