### ISSUE TITLE
kci_build: omitting --yaml-config causes an AttributeError

### ISSUE THREAD

**Issue by ConchuOD** [kernelci/kernelci-core#1647]
Hey!

Running kci_build in a directory containing a yaml config file but not specifying --yaml-config=. produced the following exception:
```
./kernelci-core/kci_build init_bmeta --build-config=next --kdir tree
Traceback (most recent call last):
  File "/home/conor/stuff/tmp/linux/./kernelci-core/kci_build", line 479, in <module>
    configs = kernelci.config.load_all(opts.get_yaml_configs())
  File "/home/conor/stuff/tmp/linux/kernelci-core/kernelci/config/__init__.py", line 189, in load_all
    data = load_all_yaml(config_paths)
  File "/home/conor/stuff/tmp/linux/kernelci-core/kernelci/config/__init__.py", line 137, in load_all_yaml
    data = load_yaml(path, validate_entries)
  File "/home/conor/stuff/tmp/linux/kernelci-core/kernelci/config/__init__.py", line 72, in load_yaml
    for yaml_path, data in _iterate_yaml_files(config_path):
  File "/home/conor/stuff/tmp/linux/kernelci-core/kernelci/config/__init__.py", line 33, in _iterate_yaml_files
    if config_path.endswith('.yaml'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

--yaml-config appears in []s in the help text, which would imply that it is an optional argument.
Adding --yaml-config=. makes things work :)
Removing the yaml file understandably produces a KeyError for "next" in the above.

Seen with bfccbafa ("rootfs-images.yaml: update rootfs URLs to 20230114.0"), and the last two kernelci-$date tags.

**Comment by gctucker** [comment]
I believe this has been resolved now.  If not the please reopen or create a new issue.
