### ISSUE TITLE
Occasional issues with git checkouts in kernel-build-trigger

### ISSUE THREAD

**Issue by gctucker** [kernelci/kernelci-core#165]
The kernel-build-trigger job occasionally hit an issue where it fails to update a git checkout using the mirror with errors as shown below:
```
Started by upstream project "kernel-tree-monitor" build number 4373
originally caused by:
 Started by user Guillaume Tucker
Obtained jenkins/build-trigger.jpl from git https://github.com/kernelci/kernelci-core.git
Resume disabled by user, switching to high-performance, low-durability mode.
Loading library kernelci@kernelci.org
Attempting to resolve kernelci.org from remote references...
 > git --version # timeout=10
 > git ls-remote -h https://github.com/kernelci/kernelci-core.git # timeout=10
Found match: refs/heads/kernelci.org revision 92edb956ae76469d2bc8dc83f5916b513331b7bd
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/kernelci/kernelci-core.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/kernelci/kernelci-core.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/kernelci/kernelci-core.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 92edb956ae76469d2bc8dc83f5916b513331b7bd (kernelci.org)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 92edb956ae76469d2bc8dc83f5916b513331b7bd
Commit message: "test-configs.yaml: upgrade Debian rootfs URLs"
 > git rev-list --no-walk 92edb956ae76469d2bc8dc83f5916b513331b7bd # timeout=10
[Pipeline] node
Running on builder01.kernelci.org - build-trigger in /home/buildslave/build-trigger/workspace/kernel-build-trigger@5
[Pipeline] {
[Pipeline] echo
    Config:    amlogic_integ
    Container: kernelci/build-base
[Pipeline] sh
+ docker pull kernelci/build-base
Using default tag: latest
latest: Pulling from kernelci/build-base
Digest: sha256:bbb368da3906ab32e2fe13cd04ec18373cd3378345db4229af65bebbb3215d7d
Status: Image is up to date for kernelci/build-base:latest
[Pipeline] sh
+ docker inspect -f . kernelci/build-base
.
[Pipeline] withDockerContainer
builder01.kernelci.org - build-trigger does not seem to be running inside a container
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Init)
[Pipeline] timeout
Timeout set to expire in 15 min
$ docker run -t -d -u 999:1000 -w /home/buildslave/build-trigger/workspace/kernel-build-trigger@5 -v /home/buildslave/build-trigger/workspace/kernel-build-trigger@5:/home/buildslave/build-trigger/workspace/kernel-build-trigger@5:rw,z -v /home/buildslave/build-trigger/workspace/kernel-build-trigger@5@tmp:/home/buildslave/build-trigger/workspace/kernel-build-trigger@5@tmp:rw,z -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** kernelci/build-base cat
[Pipeline] {
[Pipeline] sh
+ rm -rf /home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core
[Pipeline] dir
Running in /home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core
[Pipeline] {
[Pipeline] git
Cloning the remote Git repository
$ docker top 09c175799ccbc0a61e68c0a9c33ae0e8825edfb2802a74d654bd89a98909a6f6 -eo pid,comm
Cloning repository https://github.com/kernelci/kernelci-core.git
 > git init /home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core # timeout=10
Fetching upstream changes from https://github.com/kernelci/kernelci-core.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/kernelci/kernelci-core.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/kernelci/kernelci-core.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/kernelci/kernelci-core.git # timeout=10
Fetching upstream changes from https://github.com/kernelci/kernelci-core.git
 > git fetch --tags --progress https://github.com/kernelci/kernelci-core.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 92edb956ae76469d2bc8dc83f5916b513331b7bd (refs/remotes/origin/kernelci.org)
Commit message: "test-configs.yaml: upgrade Debian rootfs URLs"
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] dir
Running in /home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core
[Pipeline] {
[Pipeline] sh
+ ./kci_build check_new_commit --config=amlogic_integ --storage=http://storage.kernelci.org
 > git rev-parse refs/remotes/origin/kernelci.org^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/kernelci.org^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 92edb956ae76469d2bc8dc83f5916b513331b7bd
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b kernelci.org 92edb956ae76469d2bc8dc83f5916b513331b7bd
[Pipeline] }
[Pipeline] // dir
[Pipeline] stage
[Pipeline] { (Tarball)
[Pipeline] dir
Running in /home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core
[Pipeline] {
[Pipeline] sh
+ ./kci_build update_mirror --config=amlogic_integ --mirror=/home/buildslave/build-trigger/workspace/kernel-build-trigger@5/linux.git
From https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux-amlogic
 + 2e4ff31d2748...f5bb70553290 for-next     -> amlogic/for-next  (forced update)
 + f24465f23522...395df5af4c78 integ        -> amlogic/integ  (forced update)
   49ed86f503be..74fc01f86f5c  v5.4/drivers -> amlogic/v5.4/drivers
   e9a12e14322d..4ccc7208c2ed  v5.4/dt64    -> amlogic/v5.4/dt64
 + f24465f23522...395df5af4c78 v5.4/integ   -> amlogic/v5.4/integ  (forced update)
[Pipeline] sh
+ ./kci_build update_repo --config=amlogic_integ --kdir=/home/buildslave/build-trigger/workspace/kernel-build-trigger@5/configs/amlogic_integ --mirror=/home/buildslave/build-trigger/workspace/kernel-build-trigger@5/linux.git
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
fatal: bad object HEAD
error: https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux-amlogic.git did not send all necessary objects

error: Could not fetch amlogic
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
error: refs/remotes/amlogic/for-next does not point to a valid object!
error: refs/remotes/amlogic/integ does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt does not point to a valid object!
error: refs/remotes/amlogic/v5.4/dt64 does not point to a valid object!
error: refs/remotes/amlogic/v5.4/integ does not point to a valid object!
fatal: bad object HEAD
error: git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git did not send all necessary objects

Traceback (most recent call last):
  File "./kci_build", line 474, in <module>
    status = args.func(configs, args)
  File "./kci_build", line 234, in __call__
    kernelci.build.update_repo(conf, args.kdir, args.mirror)
  File "/home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core/kernelci/build.py", line 196, in update_repo
    _fetch_tags(path)
  File "/home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core/kernelci/build.py", line 162, in _fetch_tags
    """.format(path=path, url=url))
  File "/home/buildslave/build-trigger/workspace/kernel-build-trigger@5/kernelci-core/kernelci/__init__.py", line 25, in shell_cmd
    return subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '
cd /home/buildslave/build-trigger/workspace/kernel-build-trigger@5/configs/amlogic_integ
git fetch --tags git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
' returned non-zero exit status 1
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
$ docker stop --time=1 09c175799ccbc0a61e68c0a9c33ae0e8825edfb2802a74d654bd89a98909a6f6
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by gctucker** [comment]
Fixed in #241.
