### ISSUE TITLE
k8s-big nodes not able to handle load and possibly rebooting

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#1683]
We have 2 clusters that are handling special, "heavy" jobs, such as allmodconfig and gki_defconfig, that have long compiling time and high RAM consumption.

During k8s review i noticed that gke_android-kernelci-external_us-east4-c_kci-big-us-east4 not allowed to scale more than 2 nodes, and have 35 jobs in queue, with oldest being 24h old.
Also several pods are restarting, i suspect even current node specs are not enough and they are doing OOM (gki_defconfig).
```
NAME                                                          READY   STATUS      RESTARTS       AGE
build-j924762-arm64-clang-14-gki-defconfig-nzdk6              1/1     Running     10 (26m ago)   14h
```
Another cluster, on azure, also have several jobs in queue, oldest is 12h old.
It is likely we need to scale up max nodes in this clusters, otherwise we will not be able to get meaningful results in time.

**Comment by nuclearcat** [comment]
Restarting jobs due bug fixed recently: https://github.com/kernelci/kernelci-core/pull/1678
This is from one of jobs logs:
```
Traceback (most recent call last):
  File "/usr/local/bin/kci_build", line 4, in <module>
    __import__('pkg_resources').run_script('kernelci==1.1', 'kci_build')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 480, in <module>
    status = opts.command(configs, opts)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 397, in __call__
    self._compress_gki_artifacts(install)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 369, in _compress_gki_artifacts
    kernel_image_name = meta.get('bmeta', 'kernel', 'image')
NameError: name 'meta' is not defined
```

**Comment by nuclearcat** [comment]
At moment we have at Azure up to 4 nodes autoscaling, and only 2 nodes (where one of them used for kubernetes stuff iself) on Google Cloud. It seems this cluster reaching capacity with our current amount of builds.
I tried to rescale cluster to match at least Azure size, but it failed: "Node scale up in zones us-east4-c associated with this pod failed: GCE quota exceeded."

**Comment by nuclearcat** [comment]
It seems issue got resolved by itself, there was just a surge in kernel builds + certain issues with stuck pods (they were looping, a s mentioned  https://github.com/kernelci/kernelci-core/issues/1683#issuecomment-1406168986)
