### ISSUE TITLE
Some ChromeOS kernel builds are failing

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2310]
Jenkins log:

+ kci_build init_bmeta --build-config=chromeos-stable_6.1-backported-arm64 --commit=7b607c925f0c37589eae60e81109062cdd133cf8 --describe=linux-6.1.y-arm64-chromeos-20240122.0 --describe-verbose=v6.1-12689-g7b607c925f0c

```
+ kci_build make_config --defconfig=cros://chromeos-6.1/arm64/chromiumos-arm64.flavour.config
Warning: user settings file format '.conf' will soon be deprecated. Please use '.toml' file format and provide 'kernelci.toml' file instead.
Traceback (most recent call last):
  File "/usr/local/bin/kci_build", line 4, in <module>
    __import__('pkg_resources').run_script('kernelci==1.1', 'kci_build')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 480, in <module>
    status = opts.command(configs, opts)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/EGG-INFO/scripts/kci_build", line 302, in __call__
    res = step.run(args.j, args.verbose, opts)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/kernelci/build.py", line 1156, in run
    self._create_cros_config(target)
  File "/usr/local/lib/python3.9/dist-packages/kernelci-1.1-py3.9.egg/kernelci/build.py", line 1098, in _create_cros_config
    f.write(tar.extractfile(file_name).read())
  File "/usr/lib/python3.9/tarfile.py", line 2104, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.9/tarfile.py", line 1790, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'chromeos/arm64/chromiumos-arm64.flavour.config' not found"
```

Probably something changed in google repository for ChromeOS?

**Comment by nuclearcat** [comment]
Fixed-by: https://github.com/kernelci/kernelci-core/pull/2312
