### ISSUE TITLE
https://git.linuxtv.org/media_tree.git keep crashing jenkins

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2358]
Jenkins keep looping on following error:
```
+ kci_build update_repo --build-config=media --kdir=/data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/configs/media --mirror=/data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/linux.git
Cloning into '/data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/configs/media'...
warning: remote HEAD refers to nonexistent ref, unable to checkout
fatal: couldn't find remote ref HEAD
Traceback (most recent call last):
  File "/usr/local/bin/kci_build", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kernelci/scripts/kci_build.py", line 485, in main
    status = opts.command(configs, opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kernelci/scripts/kci_build.py", line 93, in __call__
    kernelci.build.update_repo(conf, args.kdir, args.mirror)
  File "/usr/local/lib/python3.11/site-packages/kernelci/build.py", line 159, in update_repo
    _fetch_tags(path, config.tree.url)
  File "/usr/local/lib/python3.11/site-packages/kernelci/build.py", line 103, in _fetch_tags
    shell_cmd("""
  File "/usr/local/lib/python3.11/site-packages/kernelci/__init__.py", line 29, in shell_cmd
    return subprocess.check_output(cmd, shell=True).decode()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '
set -e
cd /data/workspace/bot.kernelci.org/build-trigger/workspace/kernel-build-trigger__2/configs/media
git fetch --tags https://git.linuxtv.org/media_tree.git
' returned non-zero exit status 128.
```

**Comment by nuclearcat** [comment]
Reviewed against current main. The media tree was disabled in https://github.com/kernelci/kernelci-core/commit/f1d53d0a, and the legacy Jenkins kci_build workflow referenced here was subsequently removed in https://github.com/kernelci/kernelci-core/commit/4e6f088a. The reported Jenkins loop is therefore no longer reachable in the supported workflow. Closing as obsolete; a new issue should be opened if the media tree is reintroduced and fails in Maestro.
