### ISSUE TITLE
Decorator doesn't catch error properly on user registration

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2383]
I know that order is wrong, this error intentional to reproduce issue:
```
./kci user add email@address.com username
Password: 
Confirm password: 
Traceback (most recent call last):
  File "/home/nuclearcat/Documents/kernelci-core/kernelci/cli/__init__.py", line 77, in call
    return func(*args, **kwargs)
  File "/home/nuclearcat/Documents/kernelci-core/kernelci/cli/user.py", line 118, in add
    api.user.add(user)
  File "/home/nuclearcat/Documents/kernelci-core/kernelci/api/latest.py", line 64, in add
    return self._post('user/register', user).json()
  File "/home/nuclearcat/Documents/kernelci-core/kernelci/api/__init__.py", line 88, in _post
    resp.raise_for_status()
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://staging.kernelci.org:9000/latest/user/register

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nuclearcat/Documents/kernelci-core/./kci", line 35, in <module>
    main()
  File "/home/nuclearcat/Documents/kernelci-core/./kci", line 31, in main
    kci()  # pylint: disable=no-value-for-parameter
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nuclearcat/Documents/kernelci-core/kernelci/cli/__init__.py", line 148, in invoke
    super().invoke(ctx)
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nuclearcat/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/nuclearcat/Documents/kernelci-core/kernelci/cli/__init__.py", line 89, in call
    '\n'.join((str(ex), detail)) if detail else ex
TypeError: sequence item 1: expected str instance, list found
```

**Comment by JenySadadia** [comment]
This should be resolved with https://github.com/kernelci/kernelci-core/pull/2369.
Could you check if you tested with the latest `main`?

**Comment by nuclearcat** [comment]
Sorry for noise, can i borrow your time machine, as you fixed it before bug got reported? :-D
Thanks a lot (actually i thought i did fetched latest code, but seems did it with mistake)

**Comment by JenySadadia** [comment]
Np :)
I just came to know about this issue recently while working on something else.
