### ISSUE TITLE
Lava log parser exception

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kernelci-core#2509]
2024-04-19T07:36:00.589307553Z Exception in thread Thread-30 (async_job_submit):
2024-04-19T07:36:00.589350484Z Traceback (most recent call last):
2024-04-19T07:36:00.589356094Z   File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
2024-04-19T07:36:00.590385824Z     self.run()
2024-04-19T07:36:00.590400091Z   File "/usr/local/lib/python3.11/threading.py", line 982, in run
2024-04-19T07:36:00.590678441Z     self._target(*self._args, **self._kwargs)
2024-04-19T07:36:00.590778298Z   File "/home/kernelci/pipeline/lava_callback.py", line 80, in async_job_submit
2024-04-19T07:36:00.591240662Z     log_parser = job_callback.get_log_parser()
2024-04-19T07:36:00.591290926Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-19T07:36:00.591296907Z   File "/usr/local/lib/python3.11/site-packages/kernelci/runtime/lava.py", line 194, in get_log_parser
2024-04-19T07:36:00.591840774Z     return LogParser(self._data['log'])
2024-04-19T07:36:00.591885848Z                      ~~~~~~~~~~^^^^^^^
2024-04-19T07:36:00.591892180Z KeyError: 'log'

**Comment by nuclearcat** [comment]
Fixed
